### ISSUE TITLE
/api/v3/alertmanager does not respect custom recipients

### ISSUE THREAD

**Issue by uriinf** [schlauerlauer/alertmanager-webhook-signal#2]
In code `/api/v2/alertmanager` is marked as deprecated. But `/api/v3/alertmanager` does not support custom `alertmanager.matchLabel: recipients` via Prometheus annotation and sends alerts to the default `signal.recipients`.

**Comment by schlauerlauer** [comment]
Hi, thanks for the issue!
Please try putting the receiver in a label instead of an annotation, like this:

```yaml
- alert: "TestAlert"
  annotations:
    message: "Test message"
  labels:
    receiver: "testreceiver"
  expr: "vector(1)"
  for: "1m"
```

let me know if this works :)
